### PR TITLE
Added Node modules audit build target for Kashti

### PR DESCRIPTION
**Pull request by saksham93**
Added Node modules audit build target for Kashti.
Refers to Issue #279

### CODE REVIEW

**Comment by radu-matei** [comment]
The make target is great - now we also need to run the target in our `brigade.js` file - similar to https://github.com/brigadecore/brigade/blob/9cd050ac7f3ea82e44cbde6164d4dbf681dc5c9b/brigade.js#L48

**Comment by radu-matei** [comment]
Also note that the target will currently fail due to #281

**Comment by saksham93** [comment]
> The make target is great - now we also need to run the target in our `brigade.js` file - similar to https://github.com/brigadecore/brigade/blob/9cd050ac7f3ea82e44cbde6164d4dbf681dc5c9b/brigade.js#L48

@radu-matei Done

**Comment by radu-matei** [comment]
Excellent!

We should hold off merging this PR until #281 is fixed, but this will be of very much help going forward, thanks a lot!

**Pull request merged**
